# Generated by Django 6.0.1 on 2026-03-08 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(choices=[('PECHO', 'Pecho'), ('ESPALDA', 'Espalda'), ('HOMBROS', 'Hombros'), ('BICEPS', 'Bíceps'), ('TRICEPS', 'Tríceps'), ('PIERNAS', 'Piernas'), ('GLUTEOS', 'Glúteos'), ('ABDOMEN', 'Abdomen'), ('CARDIO', 'Cardio'), ('FULL_BODY', 'Full Body')], default='FULL_BODY', max_length=20)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración estimada en minutos')),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='INTERMEDIO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suscripcion_activa',
            field=models.BooleanField(default=False, help_text='Indica si el socio tiene membresía activa'),
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.CharField(default='12', help_text='Ej: 12, 10-12, hasta el fallo', max_length=20)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='accounts.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio en Rutina',
                'verbose_name_plural': 'Ejercicios en Rutina',
                'ordering': ['orden'],
                'unique_together': {('rutina', 'ejercicio')},
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas', through='accounts.RutinaEjercicio', to='accounts.ejercicio'),
        ),
        migrations.CreateModel(
            name='PlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para este día')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_semanales', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='accounts.rutina')),
            ],
            options={
                'verbose_name': 'Plan Semanal',
                'verbose_name_plural': 'Planes Semanales',
                'ordering': ['dia_semana'],
                'unique_together': {('usuario', 'dia_semana')},
            },
        ),
    ]
