# Generated by Django 6.0.1 on 2026-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ejercicio_rutina_user_altura_user_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('PESO_LIBRE', 'Peso Libre'), ('MAQUINA', 'Máquina'), ('CARDIO', 'Cardio'), ('ACCESORIO', 'Accesorio'), ('CALISTENIA', 'Calistenia')], default='ACCESORIO', max_length=20)),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='equipamientos',
            field=models.ManyToManyField(blank=True, related_name='ejercicios', to='accounts.equipamiento'),
        ),
    ]
