# Generated by Django 6.0.1 on 2026-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_equipamiento_ejercicio_equipamientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='dificultad',
            field=models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='INTERMEDIO', max_length=20),
        ),
    ]
