# Generated by Django 6.0.1 on 2026-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ejercicio_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
