# Generated by Django 6.0.1 on 2026-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ejercicio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipamientos_preferidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_preferencia', to='accounts.equipamiento'),
        ),
    ]
