# Generated by Django 6.0.1 on 2026-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_equipamientos_preferidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del usuario', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', help_text='Nivel de experiencia en entrenamiento', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='objetivo',
            field=models.CharField(choices=[('PERDER_PESO', 'Perder Peso'), ('GANAR_MASA', 'Ganar Masa Muscular'), ('TONIFICAR', 'Tonificar'), ('FUERZA', 'Aumentar Fuerza'), ('RESISTENCIA', 'Mejorar Resistencia'), ('SALUD_GENERAL', 'Salud General')], default='SALUD_GENERAL', help_text='Objetivo principal de entrenamiento', max_length=20),
        ),
    ]
