# Generated by Django 6.0.1 on 2026-03-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_english_domain_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['name'], 'verbose_name': 'Routine', 'verbose_name_plural': 'Routines'},
        ),
        migrations.AlterModelOptions(
            name='routineexercise',
            options={'ordering': ['order'], 'verbose_name': 'Exercise in Routine', 'verbose_name_plural': 'Exercises in Routine'},
        ),
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['weekday'], 'verbose_name': 'Weekly Plan', 'verbose_name_plural': 'Weekly Plans'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('WEIGHTS', 'Weights'), ('MACHINE', 'Machine'), ('CARDIO', 'Cardio'), ('ACCESSORY', 'Accessory'), ('CALISTHENICS', 'Calisthenics')], default='ACCESSORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='accounts.equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('ARMS', 'Arms'), ('CORE', 'Core'), ('FULL_BODY', 'Full Body')], default='FULL_BODY', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='routines', through='accounts.RoutineExercise', to='accounts.exercise'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='repetitions',
            field=models.CharField(default='12', help_text='Ex: 12, 10-12, to failure', max_length=20),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='accounts.routine'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_subscription',
            field=models.BooleanField(default=False, help_text='Indicates if the member has an active subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='User age', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('GAIN_MUSCLE', 'Gain Muscle'), ('TONE', 'Tone'), ('STRENGTH', 'Increase Strength'), ('ENDURANCE', 'Improve Endurance'), ('GENERAL_HEALTH', 'General Health')], default='GENERAL_HEALTH', help_text='Primary training goal', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', help_text='Training experience level', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_equipment',
            field=models.ManyToManyField(blank=True, related_name='users_with_preference', to='accounts.equipment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this day'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.routine'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
