# Generated by Django 6.0.1 on 2026-03-11 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_equipment_options_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_weekdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Training Weekday',
                'verbose_name_plural': 'User Training Weekdays',
                'ordering': ['weekday'],
                'unique_together': {('user', 'weekday')},
            },
        ),
    ]
