services:
  web:
    build: ./backend
    command: >
      sh -c "
      until python /code/manage.py migrate --noinput; do
        echo 'Waiting for database...';
        sleep 2;
      done &&
      python /code/manage.py seed_initial_data &&
      python /code/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
